import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET /api/bin-locations - List bin locations with pagination and search
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams
    const page = parseInt(searchParams.get('page') || '1')
    const limit = parseInt(searchParams.get('limit') || '50')
    const search = searchParams.get('search') || ''
    const isActive = searchParams.get('isActive')

    const skip = (page - 1) * limit

    // Build where clause
    const where: Record<string, unknown> = {}

    if (search) {
      where.OR = [
        { code: { contains: search, mode: 'insensitive' } },
        { name: { contains: search, mode: 'insensitive' } },
        { description: { contains: search, mode: 'insensitive' } }
      ]
    }

    if (isActive !== null && isActive !== undefined && isActive !== '') {
      where.isActive = isActive === 'true'
    }

    // Get total count for pagination
    const total = await prisma.binLocation.count({ where })

    // Get bin locations with item counts
    const binLocations = await prisma.binLocation.findMany({
      where,
      skip,
      take: limit,
      orderBy: { code: 'asc' },
      include: {
        _count: {
          select: {
            masterParts: true,
            extrusionVariants: true
          }
        }
      }
    })

    return NextResponse.json({
      binLocations,
      pagination: {
        page,
        limit,
        total,
        pages: Math.ceil(total / limit)
      }
    })
  } catch (error) {
    console.error('Error fetching bin locations:', error)
    return NextResponse.json(
      { error: 'Failed to fetch bin locations' },
      { status: 500 }
    )
  }
}

// POST /api/bin-locations - Create a new bin location
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { code, name, description } = body

    // Validate required fields
    if (!code || !name) {
      return NextResponse.json(
        { error: 'Code and name are required' },
        { status: 400 }
      )
    }

    // Check if code already exists
    const existing = await prisma.binLocation.findUnique({
      where: { code }
    })

    if (existing) {
      return NextResponse.json(
        { error: 'A bin location with this code already exists' },
        { status: 400 }
      )
    }

    // Create bin location (accessToken is auto-generated by @default(uuid()))
    const binLocation = await prisma.binLocation.create({
      data: {
        code,
        name,
        description: description || null
      },
      include: {
        _count: {
          select: {
            masterParts: true,
            extrusionVariants: true
          }
        }
      }
    })

    return NextResponse.json(binLocation, { status: 201 })
  } catch (error) {
    console.error('Error creating bin location:', error)
    return NextResponse.json(
      { error: 'Failed to create bin location' },
      { status: 500 }
    )
  }
}
